snt_immobilier:
    resource: "@SNTImmobilierBundle/Resources/config/routing.yml"
    prefix:   /immobilier

# import routes from a controller class
utilisateur:
    resource: "@SNTImmobilierBundle/Controller/RoleController.php"
    type:     annotation

role:
    resource: "@SNTImmobilierBundle/Controller/AdminController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
