<?php

namespace SNT\ImmobilierBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function findUserByLogin($login){
        $user = $this->createQueryBuilder('u')
                   ->where('u.login = :log')
                   ->setParameter('log', $login)
                   ->getQuery()
                   ->getResult();
                   
                   
    }
    */
}
